name: Sync File and Repository Weekly and Manually

on:
  schedule:
    - cron: '0 3 */2 * *'
  workflow_dispatch:

jobs:
  sync-and-replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Sync with Upstream
      run: |
        echo "Adding upstream remote repository..."
        git remote add upstream https://github.com/xiaorouji/openwrt-passwall2.git || echo "Upstream already added."
        
        echo "Fetching all changes including tags from upstream..."
        git fetch upstream --tags

        echo "Stashing local changes for specific files..."
        git stash push -m "Preserve important files" \
          ./translate_files.py \
          ./.github/workflows/sync_file.yml \
          ./.github/workflows/translate.yml || echo "Nothing to stash."
        
        echo "Rebasing changes from upstream/main..."
        git rebase upstream/main || {
          echo "Rebase encountered conflicts. Resolving automatically..."
          git rebase --abort
          git merge upstream/main -X theirs || echo "Merge conflicts resolved using upstream changes."
        }
        
        echo "Applying stashed changes..."
        git stash pop || echo "No stash to apply."

        echo "Pushing rebased changes to origin..."
        git push --force-with-lease origin main || echo "Push failed."
        
        echo "Pushing tags to origin..."
        git push origin --tags || echo "Tag push failed."

    - name: Force Replace File
      run: |
        echo "Removing old status.htm file..."
        rm -f luci-app-passwall2/luasrc/view/passwall2/global/status.htm || echo "File does not exist."
        
        echo "Downloading new status.htm file..."
        curl -fSL -o luci-app-passwall2/luasrc/view/passwall2/global/status.htm \
          https://raw.githubusercontent.com/peditx/iranIPS/refs/heads/main/.files/lowspc/main/new/backup/status.htm
        
        echo "Downloaded file content:"
        cat luci-app-passwall2/luasrc/view/passwall2/global/status.htm
        
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        
        echo "Adding changes to git..."
        git add luci-app-passwall2/luasrc/view/passwall2/global/status.htm
        git commit -m "Forced update of status.htm" || echo "No changes to commit."
        
        echo "Pushing changes to remote repository..."
        git push origin main || echo "Push failed."
